CREATE TABLE Test_Secop2_ContratosElectronicos (
[Nombre Entidad] varchar(250), 
[Nit Entidad] varchar(250), 
 [Departamento] varchar(250), 
 [Ciudad] varchar(250), 
 [Localización] varchar(250), 
 [Orden] varchar(250), 
 [Sector] varchar(250), 
 [Rama] varchar(250), 
 [Entidad Centralizada] varchar(250), 
 [Proceso de Compra] varchar(250), 
 [ID Contrato] varchar(250), 
 [Referencia del Contrato] varchar(250), 
 [Estado Contrato] varchar(250), 
 [Codigo de Categoria Principal] varchar(250), 
 [Tipo de Contrato] varchar(250), 
 [Modalidad de Contratacion] varchar(250), 
 [Justificacion Modalidad de Contratacion] varchar(250), 
 [Fecha de Firma] varchar(250), 
 [Fecha de Inicio del Contrato] varchar(250), 
 [Fecha de Fin del Contrato] varchar(250), 
 [Fecha de Inicio de Ejecucion] varchar(250), 
 [Fecha de Fin de Ejecucion] varchar(250), 
 [Condiciones de Entrega] varchar(250), 
 [TipoDocProveedor] varchar(250), 
 [Documento Proveedor] varchar(250), 
 [Proveedor Adjudicado] varchar(250), 
 [Es Grupo] varchar(250), 
 [Es Pyme] varchar(250), 
 [Habilita Pago Adelantado] varchar(250), 
 [Liquidación] varchar(250), 
 [Obligación Ambiental] varchar(250), 
 [Obligaciones Postconsumo] varchar(250), 
 [Reversion] varchar(250), 
 [Valor del Contrato] varchar(250), 
 [Valor de pago adelantado] varchar(250), 
 [Valor Facturado] varchar(250), 
 [Valor Pendiente de Pago] varchar(250), 
 [Valor Pagado] varchar(250), 
 [Valor Amortizado] varchar(250), 
 [Valor Pendiente de Amortizacion] varchar(250), 
 [Valor Pendiente de Ejecucion] varchar(250), 
 [Estado BPIN] varchar(250), 
 [Código BPIN] varchar(250), 
 [Anno BPIN] varchar(250), 
 [Saldo CDP] varchar(250), 
 [Saldo Vigencia] varchar(250), 
 [EsPostConflicto] varchar(250), 
 [URLProceso] varchar(250), 
 [Destino Gasto] varchar(250), 
 [Origen de los Recursos] varchar(250), 
 [Dias Adicionados] varchar(250), 
 [Puntos del Acuerdo] varchar(250), 
 [Pilares del Acuerdo] varchar(250), 
 [Nombre Representante Legal] varchar(250), 
 [Nacionalidad Representante Legal] varchar(250), 
 [Tipo de Identificación Representante Legal] varchar(250), 
 [Identificación Representante Legal] varchar(250), 
 [Género Representante Legal] varchar(250), 
 [Presupuesto General de la Nacion – PGN] varchar(250), 
 [Sistema General de Participaciones] varchar(250), 
 [Sistema General de Regalías] varchar(250), 
 [Recursos Propios (Alcaldías, Gobernaciones y Resguardos Indígenas)] varchar(250), 
 [Recursos de Credito] varchar(250), 
 [Recursos Propios] varchar(250), 
 [Ultima Actualizacion] varchar(250), 
 [Codigo Entidad] varchar(250), 
 [Fecha Inicio Liquidacion] varchar(250), 
 [Fecha Fin Liquidacion] varchar(250), 
 [Codigo Proveedor] varchar(250)
)