CREATE TABLE Test_Secop2_MultasYSanciones (
	[ID Proceso] VARCHAR(250)
	, [Referencia Proceso]  VARCHAR(250)
	, [ID Contrato]  VARCHAR(250)
	, [Codigo Entidad Creadora]  VARCHAR(250)
	, [Nombre Entidad Creadora]  VARCHAR(250)
	, [ Codigo Proveedor Objeto de la Multa]  VARCHAR(250)
	, [Nombre Proveedor Objeto de la Multa]  VARCHAR(250)
	, [Valor]  VARCHAR(250)
	, [Valor Pagado]  VARCHAR(250)
	, [Fecha Evento]  VARCHAR(250)
	, [Aplico Garantias]  VARCHAR(250)
	, [Numero de Acto]  VARCHAR(250)
	, [Tipo de Sancion]  VARCHAR(250)
	, [Descripcion Otro Tipo De Sancion]  VARCHAR(250)
	, [Estado]  VARCHAR(250)
	, [Tipo]  VARCHAR(250)
	, [Numero de Version]  VARCHAR(250)
);