/****** Object:  Table [dbo].[Prod_Secop2_ContratosElectronicos]    Script Date: 5/15/2023 9:07:51 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Prod_Secop2_ContratosElectronicos](
	[Nombre Entidad] [varchar](250) NULL,
	[Nit Entidad] [varchar](250) NULL,
	[Departamento] [varchar](250) NULL,
	[Ciudad] [varchar](250) NULL,
	[Localización] [varchar](250) NULL,
	[Orden] [varchar](250) NULL,
	[Sector] [varchar](250) NULL,
	[Rama] [varchar](250) NULL,
	[Entidad Centralizada] [varchar](250) NULL,
	[Proceso de Compra] [varchar](250) NULL,
	[ID Contrato] [varchar](250) NULL,
	[Referencia del Contrato] [varchar](250) NULL,
	[Estado Contrato] [varchar](250) NULL,
	[Codigo de Categoria Principal] [varchar](250) NULL,
	[Tipo de Contrato] [varchar](250) NULL,
	[Modalidad de Contratacion] [varchar](250) NULL,
	[Justificacion Modalidad de Contratacion] [varchar](250) NULL,
	[Fecha de Firma] [date] NULL,
	[Fecha de Inicio del Contrato] [date] NULL,
	[Fecha de Fin del Contrato] [date] NULL,
	[Fecha de Inicio de Ejecucion] [date] NULL,
	[Fecha de Fin de Ejecucion] [date] NULL,
	[Condiciones de Entrega] [varchar](250) NULL,
	[TipoDocProveedor] [varchar](250) NULL,
	[Documento Proveedor] [varchar](250) NULL,
	[Proveedor Adjudicado] [varchar](250) NULL,
	[Es Grupo] [varchar](250) NULL,
	[Es Pyme] [varchar](250) NULL,
	[Habilita Pago Adelantado] [varchar](250) NULL,
	[Liquidación] [varchar](250) NULL,
	[Obligación Ambiental] [varchar](250) NULL,
	[Obligaciones Postconsumo] [varchar](250) NULL,
	[Reversion] [varchar](250) NULL,
	[Valor del Contrato] [bigint] NULL,
	[Valor de pago adelantado] [bigint] NULL,
	[Valor Facturado] [bigint] NULL,
	[Valor Pendiente de Pago] [bigint] NULL,
	[Valor Pagado] [bigint] NULL,
	[Valor Amortizado] [bigint] NULL,
	[Valor Pendiente de Amortizacion] [bigint] NULL,
	[Valor Pendiente de Ejecucion] [bigint] NULL,
	[Estado BPIN] [varchar](250) NULL,
	[Código BPIN] [varchar](250) NULL,
	[Anno BPIN] [varchar](250) NULL,
	[Saldo CDP] [bigint] NULL,
	[Saldo Vigencia] [bigint] NULL,
	[EsPostConflicto] [varchar](250) NULL,
	[URLProceso] [varchar](250) NULL,
	[Destino Gasto] [varchar](250) NULL,
	[Origen de los Recursos] [varchar](250) NULL,
	[Dias Adicionados] [int] NULL,
	[Puntos del Acuerdo] [varchar](250) NULL,
	[Pilares del Acuerdo] [varchar](250) NULL,
	[Nombre Representante Legal] [varchar](250) NULL,
	[Nacionalidad Representante Legal] [varchar](250) NULL,
	[Tipo de Identificación Representante Legal] [varchar](250) NULL,
	[Identificación Representante Legal] [varchar](250) NULL,
	[Género Representante Legal] [varchar](250) NULL,
	[Presupuesto General de la Nacion – PGN] [bigint] NULL,
	[Sistema General de Participaciones] [bigint] NULL,
	[Sistema General de Regalías] [bigint] NULL,
	[Recursos Propios (Alcaldías, Gobernaciones y Resguardos Indígenas)] [bigint] NULL,
	[Recursos de Credito] [bigint] NULL,
	[Recursos Propios] [bigint] NULL,
	[Ultima Actualizacion] [date] NULL,
	[Codigo Entidad] [varchar](250) NULL,
	[Fecha Inicio Liquidacion] [date] NULL,
	[Fecha Fin Liquidacion] [date] NULL,
	[Codigo Proveedor] [varchar](250) NULL
) ON [PRIMARY]
GO


