/****** Object:  Table [dbo].[Prod_SabanaAnalitica]    Script Date: 5/15/2023 9:08:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Prod_SabanaAnalitica](
	[Pro_Entidad] [varchar](250) NULL,
	[Pro_Nit Entidad] [varchar](250) NULL,
	[Pro_Departamento Entidad] [varchar](250) NULL,
	[Pro_Ciudad Entidad] [varchar](250) NULL,
	[Pro_OrdenEntidad] [varchar](250) NULL,
	[Pro_Entidad Centralizada] [varchar](250) NULL,
	[Pro_ID del Proceso] [varchar](200) NULL,
	[Pro_Referencia del Proceso] [varchar](200) NULL,
	[Pro_PCI] [varchar](200) NULL,
	[Pro_ID del Portafolio] [varchar](200) NULL,
	[Pro_Nombre del Procedimiento] [varchar](200) NULL,
	[Pro_Fase] [varchar](200) NULL,
	[Pro_Fecha de Publicacion del Proceso] [datetime] NULL,
	[Pro_Fecha de Ultima Publicación] [datetime] NULL,
	[Pro_Fecha de Publicacion (Manifestacion de Interes)] [datetime] NULL,
	[Pro_Fecha de Publicacion (Fase Borrador)] [datetime] NULL,
	[Pro_Fecha de Publicacion (Fase Seleccion)] [datetime] NULL,
	[Pro_Precio Base] [float] NULL,
	[Pro_Modalidad de Contratacion] [varchar](250) NULL,
	[Pro_Justificación Modalidad de Contratación] [varchar](200) NULL,
	[Pro_Duracion] [int] NULL,
	[Pro_Unidad de Duracion] [varchar](200) NULL,
	[Pro_Fecha de Recepcion de Respuestas] [datetime] NULL,
	[Pro_Fecha de Apertura de Respuesta] [datetime] NULL,
	[Pro_Fecha de Apertura Efectiva] [datetime] NULL,
	[Pro_Ciudad de la Unidad de Contratación] [varchar](200) NULL,
	[Pro_Nombre de la Unidad de Contratación] [varchar](200) NULL,
	[Pro_Proveedores Invitados] [int] NULL,
	[Pro_Proveedores con Invitacion Directa] [int] NULL,
	[Pro_Visualizaciones del Procedimiento] [int] NULL,
	[Pro_Proveedores que Manifestaron Interes] [int] NULL,
	[Pro_Respuestas al Procedimiento] [int] NULL,
	[Pro_Respuestas Externas] [int] NULL,
	[Pro_Conteo de Respuestas a Ofertas] [int] NULL,
	[Pro_Proveedores Unicos con Respuestas] [int] NULL,
	[Pro_Numero de Lotes] [int] NULL,
	[Pro_Estado del Procedimiento] [varchar](200) NULL,
	[Pro_ID Estado del Procedimiento] [varchar](200) NULL,
	[Pro_Adjudicado] [varchar](200) NULL,
	[Pro_ID Adjudicacion] [varchar](200) NULL,
	[Pro_CodigoProveedor] [varchar](250) NULL,
	[Pro_Departamento Proveedor] [varchar](200) NULL,
	[Pro_Ciudad Proveedor] [varchar](200) NULL,
	[Pro_Fecha Adjudicacion] [datetime] NULL,
	[Pro_Valor Total Adjudicacion] [float] NULL,
	[Pro_Nombre del Adjudicador] [varchar](200) NULL,
	[Pro_Nombre del Proveedor Adjudicado] [varchar](250) NULL,
	[Pro_NIT del Proveedor Adjudicado] [varchar](250) NULL,
	[Pro_Codigo Principal de Categoria] [varchar](200) NULL,
	[Pro_Estado de Apertura del Proceso] [varchar](200) NULL,
	[Pro_Tipo de Contrato] [varchar](250) NULL,
	[Pro_Subtipo de Contrato] [varchar](200) NULL,
	[Pro_URLProceso] [varchar](250) NULL,
	[Pro_Codigo Entidad] [varchar](250) NULL,
	[Pro_Estado Resumen] [varchar](200) NULL,
	[Con_Orden] [varchar](250) NULL,
	[Con_Sector] [varchar](250) NULL,
	[Con_Rama] [varchar](250) NULL,
	[Con_ID Contrato] [varchar](250) NULL,
	[Con_Referencia del Contrato] [varchar](250) NULL,
	[Con_Estado Contrato] [varchar](250) NULL,
	[Con_Tipo de Contrato] [varchar](250) NULL,
	[Con_Fecha de Firma] [date] NULL,
	[Con_Fecha de Inicio del Contrato] [date] NULL,
	[Con_Fecha de Fin del Contrato] [date] NULL,
	[Con_Fecha de Inicio de Ejecucion] [date] NULL,
	[Con_Fecha de Fin de Ejecucion] [date] NULL,
	[Con_Valor del Contrato] [bigint] NULL,
	[Con_Valor de pago adelantado] [bigint] NULL,
	[Con_Valor Facturado] [bigint] NULL,
	[Con_Valor Pendiente de Pago] [bigint] NULL,
	[Con_Valor Pagado] [bigint] NULL,
	[Con_Valor Amortizado] [bigint] NULL,
	[Con_Valor Pendiente de Amortizacion] [bigint] NULL,
	[Con_Valor Pendiente de Ejecucion] [bigint] NULL,
	[Con_Dias Adicionados] [int] NULL,
	[Con_Fecha Inicio Liquidacion] [date] NULL,
	[Con_Fecha Fin Liquidacion] [date] NULL,
	[Cat_Extraccion] [varchar](30) NOT NULL,
	[FueMultado] [varchar](7) NULL
) ON [PRIMARY]
GO


