/****** Object:  Table [dbo].[Test_Secop2_ContratosElectronicos]    Script Date: 5/15/2023 9:05:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Test_Secop2_ContratosElectronicos](
	[Nombre Entidad] [varchar](250) NULL,
	[Nit Entidad] [varchar](250) NULL,
	[Departamento] [varchar](250) NULL,
	[Ciudad] [varchar](250) NULL,
	[Localización] [varchar](250) NULL,
	[Orden] [varchar](250) NULL,
	[Sector] [varchar](250) NULL,
	[Rama] [varchar](250) NULL,
	[Entidad Centralizada] [varchar](250) NULL,
	[Proceso de Compra] [varchar](250) NULL,
	[ID Contrato] [varchar](250) NULL,
	[Referencia del Contrato] [varchar](250) NULL,
	[Estado Contrato] [varchar](250) NULL,
	[Codigo de Categoria Principal] [varchar](250) NULL,
	[Tipo de Contrato] [varchar](250) NULL,
	[Modalidad de Contratacion] [varchar](250) NULL,
	[Justificacion Modalidad de Contratacion] [varchar](250) NULL,
	[Fecha de Firma] [varchar](250) NULL,
	[Fecha de Inicio del Contrato] [varchar](250) NULL,
	[Fecha de Fin del Contrato] [varchar](250) NULL,
	[Fecha de Inicio de Ejecucion] [varchar](250) NULL,
	[Fecha de Fin de Ejecucion] [varchar](250) NULL,
	[Condiciones de Entrega] [varchar](250) NULL,
	[TipoDocProveedor] [varchar](250) NULL,
	[Documento Proveedor] [varchar](250) NULL,
	[Proveedor Adjudicado] [varchar](250) NULL,
	[Es Grupo] [varchar](250) NULL,
	[Es Pyme] [varchar](250) NULL,
	[Habilita Pago Adelantado] [varchar](250) NULL,
	[Liquidación] [varchar](250) NULL,
	[Obligación Ambiental] [varchar](250) NULL,
	[Obligaciones Postconsumo] [varchar](250) NULL,
	[Reversion] [varchar](250) NULL,
	[Valor del Contrato] [varchar](250) NULL,
	[Valor de pago adelantado] [varchar](250) NULL,
	[Valor Facturado] [varchar](250) NULL,
	[Valor Pendiente de Pago] [varchar](250) NULL,
	[Valor Pagado] [varchar](250) NULL,
	[Valor Amortizado] [varchar](250) NULL,
	[Valor Pendiente de Amortizacion] [varchar](250) NULL,
	[Valor Pendiente de Ejecucion] [varchar](250) NULL,
	[Estado BPIN] [varchar](250) NULL,
	[Código BPIN] [varchar](250) NULL,
	[Anno BPIN] [varchar](250) NULL,
	[Saldo CDP] [varchar](250) NULL,
	[Saldo Vigencia] [varchar](250) NULL,
	[EsPostConflicto] [varchar](250) NULL,
	[URLProceso] [varchar](250) NULL,
	[Destino Gasto] [varchar](250) NULL,
	[Origen de los Recursos] [varchar](250) NULL,
	[Dias Adicionados] [varchar](250) NULL,
	[Puntos del Acuerdo] [varchar](250) NULL,
	[Pilares del Acuerdo] [varchar](250) NULL,
	[Nombre Representante Legal] [varchar](250) NULL,
	[Nacionalidad Representante Legal] [varchar](250) NULL,
	[Tipo de Identificación Representante Legal] [varchar](250) NULL,
	[Identificación Representante Legal] [varchar](250) NULL,
	[Género Representante Legal] [varchar](250) NULL,
	[Presupuesto General de la Nacion – PGN] [varchar](250) NULL,
	[Sistema General de Participaciones] [varchar](250) NULL,
	[Sistema General de Regalías] [varchar](250) NULL,
	[Recursos Propios (Alcaldías, Gobernaciones y Resguardos Indígenas)] [varchar](250) NULL,
	[Recursos de Credito] [varchar](250) NULL,
	[Recursos Propios] [varchar](250) NULL,
	[Ultima Actualizacion] [varchar](250) NULL,
	[Codigo Entidad] [varchar](250) NULL,
	[Fecha Inicio Liquidacion] [varchar](250) NULL,
	[Fecha Fin Liquidacion] [varchar](250) NULL,
	[Codigo Proveedor] [varchar](250) NULL
) ON [PRIMARY]
GO


